default_language_version:
  python: python3.8
exclude: ^.stubs/
repos:
  - repo: https://github.com/psf/black
    rev: "21.12b0"
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile black]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile black]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          [--in-place, --remove-all-unused-imports, --remove-unused-variable]

  - repo: https://github.com/sourcery-ai/sourcery
    rev: v0.9.8 # Get the latest tag from https://github.com/sourcery-ai/sourcery/tags
    hooks:
      - id: sourcery
      # - args: [--in-place]  Automatically apply the refactorings in the hook

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: trailing-whitespace
      - id: check-vcs-permalinks
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
      - id: check-case-conflict
      - id: check-merge-conflict

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks.
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
